config/routes.rb
Rails.application.routes.draw do


  get 'notifications/index'

 resources :friendships
   resources :notifications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :friends
  resources :users do
    collection do
      get :autocomplete
    end
      resources :orders do
            resources :order_details
        end
      resources :groups

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/add_member' => 'groups#add_member'
  post '/get_all_members' => 'groups#get_all_members'
  # invite_friend
  post '/invite_friend' => 'friends#invite_friend'
  post '/get_all_orders' => 'order_details#get_all_orders'

end

app/models/group.rb
class Group < ApplicationRecord
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  belongs_to :user
  # has_and_belongs_to_many :users
  acts_as_followable
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @user=current_user
    @groups = Group.all
    @group = Group.new
    # redirect_back(fallback_location: user_groups_path)
  end

  # @user.all_following

  def show
  end

  def add_member
    @user=current_user
    @member = User.find_by name: params[:name]
    @group = Group.find params[:g_id]
    respond_to do |format|
      if @member!=nil and @group!=nil and @user.friends.include? @member
          @member.follow(@group)
          format.json { render json: @member.to_json }
      else
          format.json { render json: (params[:name]).to_json }
      end
    end
  end

  def get_all_members
    require "json"
    @group = Group.find params[:g_id]
    @members=@group.followers
    @data={"members": @members}
    respond_to do |format|
    if @members!=nil and @group!=nil
        format.json { render json: @data.to_json }
    else
        format.json { render json: ('something wrong!').to_json }
    end
    end

  end
  # GET /groups/new
  def new
    @user=current_user
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @user=current_user
    @group = @user.groups.new({:name => params[:name], :user_id => params[:user_id]})
    respond_to do |format|
      if @group.save
        format.json { render json: Group.last.to_json }
      else
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.json { render json: "Deleted success.."}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for([@user,@group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.hidden_field :user_id ,value: @user.id %>
  </div>

  <div class="actions">
    <%= f.submit "add group" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="container">
  <div class="page-header">
  <h1>Groups</h1>
</div>
</div>

<div class="container">
<div class="text-center">
<div class="row">
<div class="col-sm-12">

  <div class="form-group">
    <label for="">group</label>
    <input class="form-control" placeholder="Group Name" type="text" id="group_name">
  </div>
     <button id="addGroup" type="button" name="button" class="btn btn-primary" >Add Group</button>
</div>
</div>

</div>
<br/>
<div class="row">
<div class="col-sm-4">
<div class="panel panel-default">
<div class="panel-heading">
  <div class="container">

    <h4>My Groups</h4>
</div>
<div id="allGroups" class="panel-body">
  <% @groups.each do |mygroup| %>
  <% if @user.id== mygroup.user_id %>
  <div id='group_row' class="row">
    <div class='col-sm-4'>
    <h5><%=mygroup.name %></h5>
  </div>
  <div class='col-sm-4'>
    <button id='add_members' name='<%=mygroup.name %>' val='<%=mygroup.id%>' class='glyphicon glyphicon-plus-sign btn btn-primary'></button>
  </div>
  <div class='col-sm-4'>
    <button id='delete_group' name='<%=mygroup.name %>' val='<%=mygroup.id%>' class='glyphicon glyphicon-remove-sign btn btn-danger'></button>
  </div>
  </div>

<br/>
<% end %>
<% end %>


</div>
</div>
</div>
</div>


<div class="col-sm-7">
<div class="panel panel-info">
<div class="panel-heading">
  <div class="container">

    <h4 id='g_title' val='0'>Group Name</h4>
</div>
</div>
<div id='group' class="panel-body">
  <div class="row">
    <div class="col-sm-12">
    <label>Your Friend Name </label>
    <input type="text" id='friend_email' name="" value="" placeholder="Friend's name">
    <button type="button" id='addFriend' name="button">add</button>
   </div>
 </div>
<div id='members'>  </div>
</div>
  </div>

</div>
</div>
</div>

</div>



</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @group.user %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>