config/routes.rb
Rails.application.routes.draw do


  get 'notifications/index'

 resources :friendships
   resources :notifications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :friends
  resources :users do
    collection do
      get :autocomplete
    end
      resources :orders do
            resources :order_details
        end
      resources :groups

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/add_member' => 'groups#add_member'
  post '/get_all_members' => 'groups#get_all_members'
  # invite_friend
  post '/invite_friend' => 'friends#invite_friend'
  post '/get_all_orders' => 'order_details#get_all_orders'

end

app/models/user.rb
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    acts_as_follower

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    devise :omniauthable, :omniauth_providers => [:facebook,:google_oauth2]
    has_and_belongs_to_many :oauth_credentials

    #mount avatar uploader
    mount_uploader :avatar, AvatarUploader

    def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
    #  user.name = auth.info.first_name
     user.name = auth.info.name
     user.avatar = auth.info.image
     user.save!
     user
      end
    end
    # searchkick word_start: [:email, :name]
    has_many :orders
    has_many :order_details
    has_many :groups
    # has_and_belongs_to_many :groups

    #class_name: "User",join_table :friendships ,foreign_key:"user_id",association_foreign_key:"friend_user_id"
    #has_and_belongs_to_many :friends,class_name: "User",join_table:  :friendships,foreign_key: :user_id,association_foreign_key: :friend_user_id
    has_many :friendships
    has_many :friends, :through => :friendships
    has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    @users = if params[:query].present?
      User.search params[:query], match: :word_start
    else
      User.all
    end
  end

  # def autocomplete
  #   render json: User.search(params[:query], autocomplete: true, limit: 10).map do |user|
  #     { name: user.name, value: user.id }
  #   end
  # end
  def autocomplete
   @user = User.order(:name).where("name LIKE ?", "%#{params[:term]}%")
   respond_to do |format|
     format.html
     format.json {
       render json: @users.map(&:name).to_json
     }
   end
 end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :reg_type, :token, :img)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Reg type</th>
      <th>Token</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.reg_type %></td>
        <td><%= user.token %></td>
        <td><%= user.img %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> -->

<h1>List All Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>

    </tr>
  </thead>

  <tbody>
    <% @users.each do |user, i| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <% friend_status = current_user.friendships.exists?(:friend_id =>user.id, :user_id => current_user.id)  ? true : false %>
        <% if(friend_status) %>
        <% friendship_id = current_user.friendships.where("friend_id = ? AND user_id = ?", user.id, current_user.id).first.id %>
          <td >
    <%= link_to "Remove Friend", friendship_path(friendship_id), :method => :delete %></td>
          <!-- <td class="table-success">Already Friends</td> -->
        <% elsif(current_user.id==user.id) %>
          <td>You</td>
        <% else %>
          <td><%= link_to 'Add Friend', friendships_path(:friend_id => user), :method => :post %></td>
        <% end %>
      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>