config/routes.rb
Rails.application.routes.draw do


  get 'notifications/index'

 resources :friendships
   resources :notifications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :friends
  resources :users do
    collection do
      get :autocomplete
    end
      resources :orders do
            resources :order_details
        end
      resources :groups

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/add_member' => 'groups#add_member'
  post '/get_all_members' => 'groups#get_all_members'
  # invite_friend
  post '/invite_friend' => 'friends#invite_friend'
  post '/get_all_orders' => 'order_details#get_all_orders'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  acts_as_followable
  mount_uploader :menu_img, MenuImgUploader

  # after_create_commit { notify }
  # private
  #
  # def notify
  #   msg = User.find(self.user_id).name + "has created an Order for " + self.meal + " from " + self.rest_name
  #   Notification.create(event: msg)
  # end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    # @order = Order.new
    @user=current_user
    @order = @user.orders.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @user=User.find params[:user_id]
    @order = @user.orders.new(order_params)
    respond_to do |format|
      if @order.save
        friends_ids = params['order']['friends']
        friends_ids.each do |friend_id|
          User.find(friend_id).follow @order
        end
        format.html { redirect_to user_orders_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update({status: false})
        format.html { redirect_to user_orders_path, notice: 'Order was successfully marked as Finished.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :index }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to user_orders_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:meal, :rest_name, :menu_img, :menu_img, :menu_img_cache, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="container">
  <div class="form-group col-sm-8 pull-left">
    <h1>Add Order</h1>
    <%= form_for [@user,@order] do |f| %>
    <div class="errors">
      <% if order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
          <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>

    <%= f.label :meal %>
    <%= f.select :meal, {Breakfast: "Breakfast", Lunch: "Lunch" , Dinner: "Dinner"} %>
    <br>
    <br>

    <%= f.label :rest_name, {class: "control-label", value: "From"}%>
    <%= f.text_field :rest_name, {class: "form-control",placeholder: "Resturant name"} %>
    <br>
    <br>

    <label for="add-friend">Invite Friends</label>
    <input type="text" name="friends" id="invite_friend" class="form-control" placeholder="Friend's name.. then press Space">
    <br>
    <br>

    <!-- Field for image upload -->
    <label>Upload Menu Image
    <div class="form-group">
      <%= f.label :menu_img do %><br />
      <%= f.file_field :menu_img, class: "form-control" %>
      <%= f.hidden_field :menu_img_cache %>
      <% end %>
    </div>
    </label>
    <br>


    <div id="invites-area"></div>
    <div id="groups-area"></div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Add Order", {class: "btn btn-info", id: "submit"} %>
    <% end %>
  </div>
  <div class="col-sm-4">

    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="container">
          <h4>Friends to Invite</h4>
        </div>
      </div>
      <div class="panel-body" id="frindesPanelBody">
        <div id='friends' class="row">
          <div class="col-sm-3">

          </div>
        </div>
      </div>
    </div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Orders</h1>
<div id="add_new_order">
  <%= link_to 'Start New Order', new_user_order_path , :style=>'display: none;'%>
  <button type="button" class="btn btn-info">Start New Order</button>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>order id</th>
      <th>Type</th>
      <th>Restrant</th>
      <th>status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.meal %></td>
      <td><%= order.rest_name %></td>
      <td><%= order.status ? "waiting" : "finished"  %></td>
      <td>
        <%= link_to ' Show Order Details ', user_order_order_details_path(user_id: current_user, order_id: order), class: "btn btn-default"  %>
        <%= order.status ? (link_to ' Finish ' , user_order_path(id: order), method: :patch, data: { confirm: 'Are you sure?' } ,class: "btn btn-default") : " "  %>
        <%= order.status ? (link_to ' Cancel ' , user_order_path(id: order), method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-default") : " "  %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Meal:</strong>
  <%= @order.meal %>
</p>

<p>
  <strong>Rest name:</strong>
  <%= @order.rest_name %>
</p>

<p>
  <strong>Menu img:</strong>
  <%= @order.menu_img %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p> -->

<%= link_to 'Edit', edit_order_path(@order) %>
<%= link_to 'Back', orders_path %>