config/routes.rb
Rails.application.routes.draw do


  get 'notifications/index'

 resources :friendships
   resources :notifications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :friends
  resources :users do
    collection do
      get :autocomplete
    end
      resources :orders do
            resources :order_details
        end
      resources :groups

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  post '/add_member' => 'groups#add_member'
  post '/get_all_members' => 'groups#get_all_members'
  # invite_friend
  post '/invite_friend' => 'friends#invite_friend'
  post '/get_all_orders' => 'order_details#get_all_orders'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Yalla Notlob</a>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>

        <%@user = current_user%>

        <li><%= link_to 'Friends', friends_path  %></li>
        <li><%= link_to 'Groups', user_groups_path(user_id:@user.id)  %></li>
        <li><%= link_to 'Orders', user_orders_path(user_id:@user.id) %></li>
      </ul>

      <%end%>

    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <!--This block is only visible to signed in admins -->

        <li><strong>  <%= current_user.name %></strong><li>
          &nbsp; &nbsp;
          <!-- <li>  <img src="<%=  current_user.avatar %>" height="50px" width="50px"/></li> -->
          <%=
          if current_user.avatar?
            image_tag(current_user.avatar,size: "50x50")
          else
            image_tag("avatarM.png", size: "50x50")
          end
          %>
          &nbsp; &nbsp;
          <%= render "layouts/notification_center" %>
          <li><%= link_to 'Logout', destroy_user_session_path,method: :delete %></li>
          <li><%= %></li>
          <!-- The block ends here -->
          <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_notification_center.html.erb
<ul class="notificator">
  <a href="#" id="open_notification">
    <i class="glyphicon glyphicon-bell notification-icon"></i>
    <span  id="notification-counter"><%= current_user.follows_by_type('Order').count %></span>
  </a>
  <div id="notificationContainer">
    <div id="notificationTitle">Notifications</div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%if current_user.follows_by_type('Order') %>
          <% current_user.follows_by_type('Order').each do |orderFollowable|  %>
          <li>
            <% order = Order.find(orderFollowable.followable_id) %>
            <%= User.find(order.user_id).name + " invited you to his order " %>
            <%= link_to('join',user_order_order_details_path(user_id: order.user_id, order_id: order)) %>
          </li>
          <% end %>
        <%end%>
      </ul>
    </div>
    <div id="notificationFooter"></div>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaNotlob</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Render navigation bar -->
    <%= render "layouts/navigation" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>